// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkIXGRAWmRTRelAZqP__zHMF5Q-kbyRA',
    appId: '1:885299720966:web:c8f8a3a40d0940fe6a2487',
    messagingSenderId: '885299720966',
    projectId: 'budget-buddy-a64aa',
    authDomain: 'budget-buddy-a64aa.firebaseapp.com',
    storageBucket: 'budget-buddy-a64aa.firebasestorage.app',
    measurementId: 'G-68CMWDZ1NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA47raK57zbRMWEOrYfZLX9J9p96mBTdJI',
    appId: '1:885299720966:android:825058513b610f8a6a2487',
    messagingSenderId: '885299720966',
    projectId: 'budget-buddy-a64aa',
    storageBucket: 'budget-buddy-a64aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIKYi4iZ73ltt9gxKyygTu3P-jpqepiNM',
    appId: '1:885299720966:ios:15d7e16f4907f4976a2487',
    messagingSenderId: '885299720966',
    projectId: 'budget-buddy-a64aa',
    storageBucket: 'budget-buddy-a64aa.firebasestorage.app',
    iosBundleId: 'com.example.dbmsPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIKYi4iZ73ltt9gxKyygTu3P-jpqepiNM',
    appId: '1:885299720966:ios:15d7e16f4907f4976a2487',
    messagingSenderId: '885299720966',
    projectId: 'budget-buddy-a64aa',
    storageBucket: 'budget-buddy-a64aa.firebasestorage.app',
    iosBundleId: 'com.example.dbmsPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdkIXGRAWmRTRelAZqP__zHMF5Q-kbyRA',
    appId: '1:885299720966:web:0cfaa991a3822fca6a2487',
    messagingSenderId: '885299720966',
    projectId: 'budget-buddy-a64aa',
    authDomain: 'budget-buddy-a64aa.firebaseapp.com',
    storageBucket: 'budget-buddy-a64aa.firebasestorage.app',
    measurementId: 'G-50K3KGSQH1',
  );
}
