name: dbms_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10
  http: ^1.5.0
  xml: ^6.6.1   # use the latest version you prefer
  image_picker: ^1.2.0
  intl: ^0.20.2
  rxdart: ^0.27.7
  fl_chart: ^1.1.1
  flutter_iconpicker: ^4.0.3
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0
  flutter_contacts: ^1.1.9+2
  shared_preferences: ^2.3.2
  timezone: ^0.10.1
  awesome_notifications: ^0.10.1
  flutter_timezone: ^5.0.0
  permission_handler: ^12.0.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon" # true or a specific icon name
  ios: true # true or a specific icon name
  image_path: "assets/icon/icon.png"
  # Optional: For Android adaptive icons
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/icon/icon_foreground.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_native_splash:
  # The color to be used for the background of the splash screen.
  color: "#D0E3FF" # Use a white background (or your app's primary color)

  # The image to be displayed in the center of the splash screen.
  image: assets/icon/icon.png 

  # Configuration for Android 12+ (Adaptive Icon style)
  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#D0E3FF"

  android: true
  ios: true 
  web: true # Set to true if you need a web splash screen
