// import 'package:firebase_core/firebase_core.dart';
// import 'package:flutter/material.dart';
// import 'auth/signup_page.dart';
// import 'firebase_options.dart'; // Make sure this file exists (generated by flutterfire configure)
// import 'package:flutter_local_notifications/flutter_local_notifications.dart';
// import 'package:timezone/data/latest_all.dart' as tz;
// import 'services/notification_service.dart'; // <-- Use the shared instance

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   tz.initializeTimeZones();

//   const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
//   const initSettings = InitializationSettings(android: androidInit);
//   await flutterLocalNotificationsPlugin.initialize(initSettings);

//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );

//   runApp(const BudgetBuddyApp());
// }

// class BudgetBuddyApp extends StatelessWidget {
//   const BudgetBuddyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       debugShowCheckedModeBanner: false,
//       home: const SignUpPage(),
//     );
//   }
// }

import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
// Note: You can remove the Firebase, local_notifications, and timezone imports 
// from main.dart because they are now handled inside SplashPage.
// import 'package:firebase_core/firebase_core.dart';
// import 'package:timezone/data/latest_all.dart' as tz; 

import 'splash_page.dart'; // Import the new SplashPage
// import 'auth/signup_page.dart';
// import 'firebase_options.dart'; 
// import 'package:flutter_local_notifications/flutter_local_notifications.dart';
// import 'services/notification_service.dart';

void main() async {
  // 1. Ensure widgets binding is initialized.
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  // 2. Preserve the native splash screen until FlutterNativeSplash.remove() is called.
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  // Note: All your heavy initialization (Firebase, Notifications, timezones) 
  // has been moved to the SplashPage's _initializeApp method.

  // 3. Run the app, starting with the SplashPage.
  runApp(const BudgetBuddyApp());
}

class BudgetBuddyApp extends StatelessWidget {
  const BudgetBuddyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      // Start the app with the dedicated SplashPage
      home: const SplashPage(), 
    );
  }
}