import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'auth/signup_page.dart';
import 'firebase_options.dart'; // Make sure this file exists (generated by flutterfire configure)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // 👈 important!
  );
  runApp(const BudgetBuddyApp());
}

class BudgetBuddyApp extends StatelessWidget {
  const BudgetBuddyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: const SignUpPage(),
    );
  }
}